title: Lightning Jek
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Create a stunning website with our clean and minimal Jekyll theme. 
  Designed for simplicity and elegance, this theme provides a perfect 
  foundation for showcasing your content. With a focus on readability and visual appeal, 
  it offers a seamless user experience across devices.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed